In [1]:
import pandas as pd
from sklearn.svm import SVC as SVM
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score 
from sklearn.feature_extraction.text import TfidfVectorizer 
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
# Load the dataset
df = pd.read_csv('sentiment_dataset.csv')
df

                                            review sentiment
0     The product quality is amazing and I love it  Positive
1          Very bad experience, will not buy again  Negative
2               Delivery was okay, nothing special   Neutral
3   Absolutely fantastic service and fast delivery  Positive
4                The item arrived damaged and late  Negative
5                             It works as expected   Neutral
6      I am extremely satisfied with this purchase  Positive
7       Worst product ever, totally waste of money  Negative
8                     Average quality, not too bad   Neutral
9                Highly recommend this to everyone  Positive
10                   Customer support is very poor  Negative
11                            The design is decent   Neutral
12    Excellent performance and great battery life  Positive
13                             Not worth the price  Negative
14                        It is fine for daily use   Neutral
15             Superb experience, will order again  Positive
16       The product stopped working after one day  Negative
17                  Nothing extraordinary but okay   Neutral
18                      Very खुश with the purchase  Positive
19              Terrible packaging and broken item  Negative
20                           The product is usable   Neutral
21                 I love the features and quality  Positive
22                         Completely disappointed  Negative
23                                 It does the job   Neutral
24             Best purchase I have made this year  Positive
25                  The color faded after one wash  Negative
26                         Just okay for the price   Neutral
27             Brilliant product and fast shipping  Positive
28                             Received wrong item  Negative
29                        Not bad, could be better   Neutral
30                Very impressive and high quality  Positive
31            Horrible experience with this seller  Negative
32                                It is acceptable   Neutral
33                           Great value for money  Positive
34                      Battery drains too quickly  Negative
35                             Average performance   Neutral
36               I am very happy with this product  Positive
37                        The material feels cheap  Negative
38                        Nothing special about it   Neutral
39                        Exceeded my expectations  Positive
40                  Late delivery and poor service  Negative
41                                   It works fine   Neutral
42                    Fantastic quality and design  Positive
43                            Not satisfied at all  Negative
44                      Okay product for daily use   Neutral
45                      Loved it, highly recommend  Positive
46                      Very disappointing quality  Negative
47                            Decent but not great   Neutral
48                   Five stars, excellent product  Positive
49                       Will never buy this again  Negative

In [4]:
checking_null_values = df.isnull().sum()
checking_duplicate_values = df.duplicated().sum()
checking_duplicate_values

np.int64(0)

In [7]:
# Feature selection
X = df.drop(columns="sentiment")
X

                                            review
0     The product quality is amazing and I love it
1          Very bad experience, will not buy again
2               Delivery was okay, nothing special
3   Absolutely fantastic service and fast delivery
4                The item arrived damaged and late
5                             It works as expected
6      I am extremely satisfied with this purchase
7       Worst product ever, totally waste of money
8                     Average quality, not too bad
9                Highly recommend this to everyone
10                   Customer support is very poor
11                            The design is decent
12    Excellent performance and great battery life
13                             Not worth the price
14                        It is fine for daily use
15             Superb experience, will order again
16       The product stopped working after one day
17                  Nothing extraordinary but okay
18                      Very खुश with the purchase
19              Terrible packaging and broken item
20                           The product is usable
21                 I love the features and quality
22                         Completely disappointed
23                                 It does the job
24             Best purchase I have made this year
25                  The color faded after one wash
26                         Just okay for the price
27             Brilliant product and fast shipping
28                             Received wrong item
29                        Not bad, could be better
30                Very impressive and high quality
31            Horrible experience with this seller
32                                It is acceptable
33                           Great value for money
34                      Battery drains too quickly
35                             Average performance
36               I am very happy with this product
37                        The material feels cheap
38                        Nothing special about it
39                        Exceeded my expectations
40                  Late delivery and poor service
41                                   It works fine
42                    Fantastic quality and design
43                            Not satisfied at all
44                      Okay product for daily use
45                      Loved it, highly recommend
46                      Very disappointing quality
47                            Decent but not great
48                   Five stars, excellent product
49                       Will never buy this again

In [8]:
y = df["sentiment"]
y

0     Positive
1     Negative
2      Neutral
3     Positive
4     Negative
5      Neutral
6     Positive
7     Negative
8      Neutral
9     Positive
10    Negative
11     Neutral
12    Positive
13    Negative
14     Neutral
15    Positive
16    Negative
17     Neutral
18    Positive
19    Negative
20     Neutral
21    Positive
22    Negative
23     Neutral
24    Positive
25    Negative
26     Neutral
27    Positive
28    Negative
29     Neutral
30    Positive
31    Negative
32     Neutral
33    Positive
34    Negative
35     Neutral
36    Positive
37    Negative
38     Neutral
39    Positive
40    Negative
41     Neutral
42    Positive
43    Negative
44     Neutral
45    Positive
46    Negative
47     Neutral
48    Positive
49    Negative
Name: sentiment, dtype: str

In [ ]:
# Convert Text to Numbers (Only for X!)
vectorizer = TfidfVectorizer()
X_numeric = vectorizer.fit_transform(X['review'])

In [17]:
# Splitting of dataset into training and testing (randomly)
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [19]:
# Train the Model
model = SVM(kernel="linear")
X_train_numeric = vectorizer.transform(X_train['review'])
model.fit(X_train_numeric, y_train)

SVC(kernel='linear')

In [20]:
from sklearn.svm import SVC

model = SVC(kernel="linear")

In [ ]:
model.fit(X_train_numeric, y_train)
predicted_y = model.predict(vectorizer.transform(X_test['review']))

predicted_y

C:\Users\E-TIME\AppData\Roaming\Python\Python314\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(

AttributeError: 'SVC' object has no attribute 'support_vectors_'

In [13]:
result = accuracy_score(predicted_y,y_test)
result

NameError: name 'predicted_y' is not defined